package com.hpzc.common.cxf.model;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2017-05-18T10:41:51.745+08:00
 * Generated source version: 3.1.4
 * 
 */
@WebService(targetNamespace = "urn:sinopec:ecc:fi:tmsno:fx", name = "TmsImsWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface TmsImsWebService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "MT_TMS_ECC_FI_TMSYXNO", targetNamespace = "urn:sinopec:ecc:fi:tmsno:fx", className = "com.hpzc.common.cxf.model.MTTMSECCFITMSYXNO")
    @WebMethod(operationName = "MT_TMS_ECC_FI_TMSYXNO")
    @ResponseWrapper(localName = "MT_TMS_ECC_FI_TMSYXNOResponse", targetNamespace = "urn:sinopec:ecc:fi:tmsno:fx", className = "com.hpzc.common.cxf.model.MTTMSECCFITMSYXNOResponse")
    public java.lang.String mtTMSECCFITMSYXNO(
        @WebParam(name = "TmsYxNo", targetNamespace = "")
        java.lang.String tmsYxNo,
        @WebParam(name = "CODE", targetNamespace = "")
        java.lang.String code,
        @WebParam(name = "YWRQ", targetNamespace = "")
        java.lang.String ywrq
    );
}
