
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.hpzc.common.cxf.model;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2017-05-18T10:41:51.730+08:00
 * Generated source version: 3.1.4
 * 
 */

@javax.jws.WebService(
                      serviceName = "TmsImsWebServiceImplService",
                      portName = "TmsImsWebServiceImplPort",
                      targetNamespace = "urn:sinopec:ecc:fi:tmsno:fx",
                      wsdlLocation = "http://localhost:8080/fsscbs/ws/tmsImsNo?wsdl",
                      endpointInterface = "com.hpzc.common.cxf.model.TmsImsWebService")
                      
public class TmsImsWebServiceImplPortImpl implements TmsImsWebService {

    private static final Logger LOG = Logger.getLogger(TmsImsWebServiceImplPortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.hpzc.common.cxf.model.TmsImsWebService#mtTMSECCFITMSYXNO(java.lang.String  tmsYxNo ,)java.lang.String  code ,)java.lang.String  ywrq )*
     */
    public java.lang.String mtTMSECCFITMSYXNO(java.lang.String tmsYxNo,java.lang.String code,java.lang.String ywrq) { 
        LOG.info("Executing operation mtTMSECCFITMSYXNO");
        System.out.println(tmsYxNo);
        System.out.println(code);
        System.out.println(ywrq);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
