
package com.hpzc.common.cxf.model;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2017-05-18T10:41:51.603+08:00
 * Generated source version: 3.1.4
 * 
 */
public final class TmsImsWebService_TmsImsWebServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("urn:sinopec:ecc:fi:tmsno:fx", "TmsImsWebServiceImplService");

    private TmsImsWebService_TmsImsWebServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = TmsImsWebServiceImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        TmsImsWebServiceImplService ss = new TmsImsWebServiceImplService(wsdlURL, SERVICE_NAME);
        TmsImsWebService port = ss.getTmsImsWebServiceImplPort();  
        
        {
        System.out.println("Invoking mtTMSECCFITMSYXNO...");
        java.lang.String _mtTMSECCFITMSYXNO_tmsYxNo = "";
        java.lang.String _mtTMSECCFITMSYXNO_code = "";
        java.lang.String _mtTMSECCFITMSYXNO_ywrq = "";
        java.lang.String _mtTMSECCFITMSYXNO__return = port.mtTMSECCFITMSYXNO(_mtTMSECCFITMSYXNO_tmsYxNo, _mtTMSECCFITMSYXNO_code, _mtTMSECCFITMSYXNO_ywrq);
        System.out.println("mtTMSECCFITMSYXNO.result=" + _mtTMSECCFITMSYXNO__return);


        }

        System.exit(0);
    }

}
