package com.hpzc.common.cxf.model;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2017-05-18T10:41:51.754+08:00
 * Generated source version: 3.1.4
 * 
 */
@WebServiceClient(name = "TmsImsWebServiceImplService", 
                  wsdlLocation = "http://localhost:8080/fsscbs/ws/tmsImsNo?wsdl",
                  targetNamespace = "urn:sinopec:ecc:fi:tmsno:fx") 
public class TmsImsWebServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:sinopec:ecc:fi:tmsno:fx", "TmsImsWebServiceImplService");
    public final static QName TmsImsWebServiceImplPort = new QName("urn:sinopec:ecc:fi:tmsno:fx", "TmsImsWebServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/fsscbs/ws/tmsImsNo?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(TmsImsWebServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/fsscbs/ws/tmsImsNo?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public TmsImsWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TmsImsWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TmsImsWebServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public TmsImsWebServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public TmsImsWebServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public TmsImsWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns TmsImsWebService
     */
    @WebEndpoint(name = "TmsImsWebServiceImplPort")
    public TmsImsWebService getTmsImsWebServiceImplPort() {
        return super.getPort(TmsImsWebServiceImplPort, TmsImsWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TmsImsWebService
     */
    @WebEndpoint(name = "TmsImsWebServiceImplPort")
    public TmsImsWebService getTmsImsWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(TmsImsWebServiceImplPort, TmsImsWebService.class, features);
    }

}
